### ISSUE TITLE
data_generator

### ISSUE THREAD

**Issue by mikaeilorfanian** [HubbeKing/EkList#1]
Why didn't you make a Django management command for for populating the db?

**Comment by HubbeKing** [comment]
The data generation script was only ever used once, to create a data fixture to use for the automated tests. Creating a Django management command for this seemed like too much work for a university project.

**Comment by mikaeilorfanian** [comment]
Are you maintaining this project? It seems like you're not interested in doing so.

**Comment by HubbeKing** [comment]
I am not currently maintaining this project, nor interested in doing so. 
There are better ways to create simple websites available, so maintaining a sloppy Django-made one seems unnecessary.
